// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhejkdfzjpnojuvoekxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoZWprZGZ6anBub2p1dm9la3hrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MzcyNTMsImV4cCI6MjA3MjQxMzI1M30.XLllt39cX0CUs_V0uMLRElKC5cvuwSAY_ce7I303sTU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});